#!/bin/bash

#openspace
OLDIFS=$IFS
IFS=$'\n'

#module
warna="\e[0;32m"

#get permission read
a=("+r" "+w" "+x" "+rw" "+rx" "+wx" "+rwx" "-r" "-w" "-x" "-rw" "-rx" "-wx" "-rwx")

#open window
winopen(){
  for i in {0..70};do
    if [[ $i -eq 0 ]];then
      printf "╭"
    elif [[ $i -eq 70 ]];then
      printf "╮"
    else
      printf "—"
    fi
  done
  echo
}

#close window
winclose(){                                                                                for i in {0..70};do
    if [[ $i -eq 0 ]];then
      printf "╰"
    elif [[ $i -eq 70 ]];then
      printf "╯"
    else
      printf "—"
    fi
  done
  echo
}

#show list
gettext(){
  a="$(expr length $1)"
  b=0
  while [[ $b -le $a ]];do
    c[$b]=${1:$b:1}; ((b++))
  done

  s=" "
  d=0; gline=$2; gspace=$((gline+a))
  for n in {0..70};do
    if [[ $n -eq 0 ]] || [[ $n -eq 70 ]];then
      printf "|"
    elif [[ $n -gt $gline ]];then
      printf "${c[d]}"; ((d++))
    fi
    if [[ $n -lt $gline ]];then
      printf "$s"
    elif [[ $n -gt $gspace ]];then
      printf "$s"
    fi
  done
  echo; unset c
}

#run tabel
winopen
for i in ${!a[@]};do
  gettext "$i. $1${a[i]}" 2
done
winclose

#closespace
IFS=$OLDIFS
